// Generated by gencpp from file robot_msgs/attack_base.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ATTACK_BASE_H
#define ROBOT_MSGS_MESSAGE_ATTACK_BASE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct attack_base_
{
  typedef attack_base_<ContainerAllocator> Type;

  attack_base_()
    : yaw(0.0)
    , flag(0)  {
    }
  attack_base_(const ContainerAllocator& _alloc)
    : yaw(0.0)
    , flag(0)  {
  (void)_alloc;
    }



   typedef float _yaw_type;
  _yaw_type yaw;

   typedef int8_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::robot_msgs::attack_base_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::attack_base_<ContainerAllocator> const> ConstPtr;

}; // struct attack_base_

typedef ::robot_msgs::attack_base_<std::allocator<void> > attack_base;

typedef boost::shared_ptr< ::robot_msgs::attack_base > attack_basePtr;
typedef boost::shared_ptr< ::robot_msgs::attack_base const> attack_baseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::attack_base_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::attack_base_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::attack_base_<ContainerAllocator1> & lhs, const ::robot_msgs::attack_base_<ContainerAllocator2> & rhs)
{
  return lhs.yaw == rhs.yaw &&
    lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::attack_base_<ContainerAllocator1> & lhs, const ::robot_msgs::attack_base_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::attack_base_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::attack_base_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::attack_base_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::attack_base_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::attack_base_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::attack_base_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::attack_base_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a64b3102681d4388f983b59c1ae894d";
  }

  static const char* value(const ::robot_msgs::attack_base_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a64b3102681d438ULL;
  static const uint64_t static_value2 = 0x8f983b59c1ae894dULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::attack_base_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/attack_base";
  }

  static const char* value(const ::robot_msgs::attack_base_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::attack_base_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 yaw\n"
"int8 flag\n"
;
  }

  static const char* value(const ::robot_msgs::attack_base_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::attack_base_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct attack_base_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::attack_base_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::attack_base_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "flag: ";
    Printer<int8_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ATTACK_BASE_H
