// Generated by gencpp from file robot_msgs/ChassisMoveStatus.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_CHASSISMOVESTATUS_H
#define ROBOT_MSGS_MESSAGE_CHASSISMOVESTATUS_H

#include <ros/service_traits.h>


#include <robot_msgs/ChassisMoveStatusRequest.h>
#include <robot_msgs/ChassisMoveStatusResponse.h>


namespace robot_msgs
{

struct ChassisMoveStatus
{

typedef ChassisMoveStatusRequest Request;
typedef ChassisMoveStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChassisMoveStatus
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::ChassisMoveStatus > {
  static const char* value()
  {
    return "0a8ab4662f6938ca464a048217cc826e";
  }

  static const char* value(const ::robot_msgs::ChassisMoveStatus&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::ChassisMoveStatus > {
  static const char* value()
  {
    return "robot_msgs/ChassisMoveStatus";
  }

  static const char* value(const ::robot_msgs::ChassisMoveStatus&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::ChassisMoveStatusRequest> should match
// service_traits::MD5Sum< ::robot_msgs::ChassisMoveStatus >
template<>
struct MD5Sum< ::robot_msgs::ChassisMoveStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::ChassisMoveStatus >::value();
  }
  static const char* value(const ::robot_msgs::ChassisMoveStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::ChassisMoveStatusRequest> should match
// service_traits::DataType< ::robot_msgs::ChassisMoveStatus >
template<>
struct DataType< ::robot_msgs::ChassisMoveStatusRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::ChassisMoveStatus >::value();
  }
  static const char* value(const ::robot_msgs::ChassisMoveStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::ChassisMoveStatusResponse> should match
// service_traits::MD5Sum< ::robot_msgs::ChassisMoveStatus >
template<>
struct MD5Sum< ::robot_msgs::ChassisMoveStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::ChassisMoveStatus >::value();
  }
  static const char* value(const ::robot_msgs::ChassisMoveStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::ChassisMoveStatusResponse> should match
// service_traits::DataType< ::robot_msgs::ChassisMoveStatus >
template<>
struct DataType< ::robot_msgs::ChassisMoveStatusResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::ChassisMoveStatus >::value();
  }
  static const char* value(const ::robot_msgs::ChassisMoveStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_CHASSISMOVESTATUS_H
