// Generated by gencpp from file robot_msgs/mainYawCtrl.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_MAINYAWCTRL_H
#define ROBOT_MSGS_MESSAGE_MAINYAWCTRL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct mainYawCtrl_
{
  typedef mainYawCtrl_<ContainerAllocator> Type;

  mainYawCtrl_()
    : yaw(0.0)
    , id(0)  {
    }
  mainYawCtrl_(const ContainerAllocator& _alloc)
    : yaw(0.0)
    , id(0)  {
  (void)_alloc;
    }



   typedef float _yaw_type;
  _yaw_type yaw;

   typedef int8_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::robot_msgs::mainYawCtrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::mainYawCtrl_<ContainerAllocator> const> ConstPtr;

}; // struct mainYawCtrl_

typedef ::robot_msgs::mainYawCtrl_<std::allocator<void> > mainYawCtrl;

typedef boost::shared_ptr< ::robot_msgs::mainYawCtrl > mainYawCtrlPtr;
typedef boost::shared_ptr< ::robot_msgs::mainYawCtrl const> mainYawCtrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::mainYawCtrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::mainYawCtrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::mainYawCtrl_<ContainerAllocator1> & lhs, const ::robot_msgs::mainYawCtrl_<ContainerAllocator2> & rhs)
{
  return lhs.yaw == rhs.yaw &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::mainYawCtrl_<ContainerAllocator1> & lhs, const ::robot_msgs::mainYawCtrl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::mainYawCtrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::mainYawCtrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::mainYawCtrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::mainYawCtrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::mainYawCtrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::mainYawCtrl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::mainYawCtrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c12ee215529067b9c49a63eae551cbc9";
  }

  static const char* value(const ::robot_msgs::mainYawCtrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc12ee215529067b9ULL;
  static const uint64_t static_value2 = 0xc49a63eae551cbc9ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::mainYawCtrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/mainYawCtrl";
  }

  static const char* value(const ::robot_msgs::mainYawCtrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::mainYawCtrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 yaw\n"
"int8 id\n"
;
  }

  static const char* value(const ::robot_msgs::mainYawCtrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::mainYawCtrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mainYawCtrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::mainYawCtrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::mainYawCtrl_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_MAINYAWCTRL_H
