(cl:defpackage robot_msgs-msg
  (:use )
  (:export
   "<EULERANGLES>"
   "EULERANGLES"
   "<PTZ_YAW>"
   "PTZ_YAW"
   "<PTZ_PERCEPTION>"
   "PTZ_PERCEPTION"
   "<TRACK_RESET>"
   "TRACK_RESET"
   "<YAW_DECISION>"
   "YAW_DECISION"
   "<ATTACK_BASE>"
   "ATTACK_BASE"
   "<BARREL>"
   "BARREL"
   "<CHASSIS>"
   "CHASSIS"
   "<COMPETITION_INFO>"
   "COMPETITION_INFO"
   "<CONTROL>"
   "CONTROL"
   "<MAINYAWCTRL>"
   "MAINYAWCTRL"
   "<ROBOT_CTRL>"
   "ROBOT_CTRL"
   "<SC_RC_MSG>"
   "SC_RC_MSG"
   "<VISION>"
   "VISION"
   "<VISION_PTS>"
   "VISION_PTS"
  ))

