// Generated by gencpp from file robot_msgs/control.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_CONTROL_H
#define ROBOT_MSGS_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct control_
{
  typedef control_<ContainerAllocator> Type;

  control_()
    : shoot_sta(0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  control_(const ContainerAllocator& _alloc)
    : shoot_sta(0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef uint16_t _shoot_sta_type;
  _shoot_sta_type shoot_sta;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::robot_msgs::control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::control_<ContainerAllocator> const> ConstPtr;

}; // struct control_

typedef ::robot_msgs::control_<std::allocator<void> > control;

typedef boost::shared_ptr< ::robot_msgs::control > controlPtr;
typedef boost::shared_ptr< ::robot_msgs::control const> controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::control_<ContainerAllocator1> & lhs, const ::robot_msgs::control_<ContainerAllocator2> & rhs)
{
  return lhs.shoot_sta == rhs.shoot_sta &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::control_<ContainerAllocator1> & lhs, const ::robot_msgs::control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c338ed0a873994cf2d713f278c2de0d";
  }

  static const char* value(const ::robot_msgs::control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c338ed0a873994cULL;
  static const uint64_t static_value2 = 0xf2d713f278c2de0dULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/control";
  }

  static const char* value(const ::robot_msgs::control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 shoot_sta\n"
"float32 pitch\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::robot_msgs::control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shoot_sta);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::control_<ContainerAllocator>& v)
  {
    s << indent << "shoot_sta: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.shoot_sta);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_CONTROL_H
