(cl:defpackage robot_msgs-srv
  (:use )
  (:export
   "CHASSISMOVESTATUS"
   "<CHASSISMOVESTATUS-REQUEST>"
   "CHASSISMOVESTATUS-REQUEST"
   "<CHASSISMOVESTATUS-RESPONSE>"
   "CHASSISMOVESTATUS-RESPONSE"
  ))

